# Generated by Django 4.2.30 on 2026-06-02 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Формат: +7(XXX)-XXX-XX-XX', regex='^\\+7\\(\\d{3}\\)-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Гостей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('visited', 'Посещение состоялось'), ('cancelled', 'Отменено')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Формат: +7(XXX)-XXX-XX-XX', regex='^\\+7\\(\\d{3}\\)-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Логин должен быть на кириллице и не менее 6 символов.', regex='^[а-яА-ЯёЁ]{6,}$')], verbose_name='Логин'),
        ),
    ]
